# =============================================================================
# Outputs
# =============================================================================

# -----------------------------------------------------------------------------
# Network Information
# -----------------------------------------------------------------------------

output "network_id" {
  description = "ID of the private network"
  value       = hcloud_network.cluster_network.id
}

output "network_name" {
  description = "Name of the private network"
  value       = hcloud_network.cluster_network.name
}

# -----------------------------------------------------------------------------
# Cluster Name (used by scripts)
# -----------------------------------------------------------------------------

output "cluster_name" {
  description = "Name of the cluster"
  value       = var.cluster_name
}

output "admin_user" {
  description = "Admin user name"
  value       = var.admin_user
}

# -----------------------------------------------------------------------------
# Control Node Information
# -----------------------------------------------------------------------------

output "control_node_id" {
  description = "ID of the control node"
  value       = hcloud_server.control_node.id
}

output "control_node_name" {
  description = "Name of the control node"
  value       = hcloud_server.control_node.name
}

output "control_node_ipv6" {
  description = "Public IPv6 address of the control node"
  value       = var.enable_public_ipv6 ? hcloud_server.control_node.ipv6_address : "disabled"
}

output "control_node_private_ip" {
  description = "Private IP of the control node"
  value       = hcloud_server_network.control_node.ip
}

# -----------------------------------------------------------------------------
# Worker Nodes Information
# -----------------------------------------------------------------------------

output "worker_node_count" {
  description = "Number of worker nodes"
  value       = var.worker_node_count
}

output "worker_node_ids" {
  description = "IDs of worker nodes"
  value       = hcloud_server.worker_node[*].id
}

output "worker_node_names" {
  description = "Names of worker nodes"
  value       = hcloud_server.worker_node[*].name
}

output "worker_node_private_ips" {
  description = "Private IPs of worker nodes"
  value       = hcloud_server_network.worker_node[*].ip
}

# -----------------------------------------------------------------------------
# SSH Keys (Private - Handle with care!)
# Only available when auto-generated (not with custom keys)
# -----------------------------------------------------------------------------

output "control_node_ssh_private_key" {
  description = "Private SSH key for control node (only if auto-generated)"
  value       = length(tls_private_key.control_node) > 0 ? tls_private_key.control_node[0].private_key_openssh : "Using custom key - manage privately"
  sensitive   = true
}

output "control_node_ssh_public_key" {
  description = "Public SSH key for control node"
  value       = local.control_node_public_key
}

output "worker_node_ssh_private_key" {
  description = "Private SSH key for worker nodes (only if auto-generated)"
  value       = length(tls_private_key.worker_node) > 0 ? tls_private_key.worker_node[0].private_key_openssh : (var.worker_node_count > 0 ? "Using custom key - manage privately" : "No workers configured")
  sensitive   = true
}

output "worker_node_ssh_public_key" {
  description = "Public SSH key for worker nodes"
  value       = var.worker_node_count > 0 ? local.worker_node_public_key : "No workers configured"
}

output "using_custom_keys" {
  description = "Whether custom SSH keys are being used"
  value = {
    control_node = var.control_node_public_key != ""
    worker_node  = var.worker_node_public_key != ""
  }
}

# -----------------------------------------------------------------------------
# SSH Config Snippet
# -----------------------------------------------------------------------------

output "ssh_config_snippet" {
  description = "SSH config snippet for ~/.ssh/config"
  value       = <<-EOT
    # =============================================================================
    # ${var.cluster_name} - Generated by OpenTofu
    # =============================================================================

    # Control Node via Cloudflare Tunnel
    Host ${var.cloudflare_tunnel_domain != "" ? var.cloudflare_tunnel_domain : "control-node"}
        HostName ${var.cloudflare_tunnel_domain != "" ? var.cloudflare_tunnel_domain : hcloud_server_network.control_node.ip}
        User ${var.admin_user}
        IdentityFile ~/.ssh/${var.cluster_name}_control-node_key
        %{if var.cloudflare_tunnel_domain != ""}ProxyCommand /opt/homebrew/bin/cloudflared access ssh --hostname %h%{endif}

    %{for i, ip in hcloud_server_network.worker_node[*].ip~}
    # Worker Node ${format("%02d", i + 1)}
    Host worker-${format("%02d", i + 1)}
        HostName ${ip}
        User ${var.admin_user}
        IdentityFile ~/.ssh/${var.cluster_name}_worker-node_key
        ProxyJump ${var.cloudflare_tunnel_domain != "" ? var.cloudflare_tunnel_domain : "control-node"}

    %{endfor~}
  EOT
}

# -----------------------------------------------------------------------------
# Next Steps
# -----------------------------------------------------------------------------

output "next_steps" {
  description = "Instructions for completing the setup"
  value       = <<-EOT

    ╔══════════════════════════════════════════════════════════════════════════════╗
    ║                              NEXT STEPS                                       ║
    ╠══════════════════════════════════════════════════════════════════════════════╣
    %{if var.control_node_public_key == ""}
    ║  1. Export SSH Keys (auto-generated):                                         ║
    ║     tofu output -raw control_node_ssh_private_key > ~/.ssh/${var.cluster_name}_control-node_key
    %{if var.worker_node_count > 0}
    ║     tofu output -raw worker_node_ssh_private_key > ~/.ssh/${var.cluster_name}_worker-node_key
    %{endif}
    ║     chmod 600 ~/.ssh/${var.cluster_name}_*_key
    %{else}
    ║  1. SSH Keys: Using your custom keys - ensure they are in ~/.ssh/            ║
    %{endif}
    ║                                                                               ║
    ║  2. Add SSH Config:                                                           ║
    ║     tofu output -raw ssh_config_snippet >> ~/.ssh/config                      ║
    ║                                                                               ║
    ║  3. Connect to Control Node (via IPv6, temporary):                            ║
    ║     ssh -i ~/.ssh/${var.cluster_name}_control-node_key ${var.admin_user}@${var.enable_public_ipv6 ? hcloud_server.control_node.ipv6_address : "N/A"}
    ║                                                                               ║
    ║  4. Install Cloudflare Tunnel on Control Node:                                ║
    ║     sudo cloudflared service install <YOUR_TUNNEL_TOKEN>                      ║
    ║                                                                               ║
    ║  5. Disable Public IPs (after Tunnel works):                                  ║
    ║     Set enable_public_ipv6 = false in terraform.tfvars                        ║
    ║     Run: tofu apply                                                           ║
    ║                                                                               ║
    ╚══════════════════════════════════════════════════════════════════════════════╝

  EOT
}
