#!/bin/bash

# =============================================================================
# Generate Ansible Inventory from OpenTofu State
# =============================================================================
# Uses SSH Host aliases from ~/.ssh/config (generated by setup-ssh.sh) for
# routing. The SSH config already contains ProxyJump/ProxyCommand, IdentityFile,
# and User for each host — the inventory just needs to point to the right alias.
#
# Prerequisites: run ./scripts/setup-ssh.sh first to generate SSH config.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ANSIBLE_DIR="$PROJECT_DIR/ansible"

# Check if we're in the right directory
if [[ ! -f "$PROJECT_DIR/main.tf" ]]; then
    echo "Error: main.tf not found. Run this script from the project directory."
    exit 1
fi

# Check for tofu/terraform
if command -v tofu &> /dev/null; then
    TF_CMD="tofu"
elif command -v terraform &> /dev/null; then
    TF_CMD="terraform"
else
    echo "Error: Neither 'tofu' nor 'terraform' found."
    exit 1
fi

cd "$PROJECT_DIR"

# Get values from Terraform output
CLUSTER_NAME=$($TF_CMD output -raw cluster_name 2>/dev/null || echo "k8s-cluster")
ADMIN_USER=$($TF_CMD output -raw admin_user 2>/dev/null || echo "kubernetes-admin")
CONTROL_COUNT=$($TF_CMD output -raw control_node_count 2>/dev/null || echo "1")
WORKER_COUNT=$($TF_CMD output -raw worker_node_count 2>/dev/null || echo "0")
TUNNEL_DOMAIN=$($TF_CMD output -raw cloudflare_tunnel_domain 2>/dev/null || echo "")
ADMIN_NODE_ENABLED=$($TF_CMD output -raw enable_admin_node 2>/dev/null || echo "false")

# Determine the SSH Host alias for the master control node.
# This must match the Host entries generated by setup-ssh.sh:
#   - Admin node enabled  → "control-node" (ProxyJump admin-node)
#   - Tunnel only         → "<tunnel_domain>" (ProxyCommand cloudflared)
#   - Neither             → "control-node" (direct)
if [[ "$ADMIN_NODE_ENABLED" == "true" ]]; then
    MASTER_SSH_HOST="control-node"
elif [[ -n "$TUNNEL_DOMAIN" && "$TUNNEL_DOMAIN" != "" ]]; then
    MASTER_SSH_HOST="$TUNNEL_DOMAIN"
else
    MASTER_SSH_HOST="control-node"
fi

# Generate inventory
cat > "$ANSIBLE_DIR/inventory.ini" << EOF
# =============================================================================
# Ansible Inventory - Generated from OpenTofu State
# Generated: $(date)
# =============================================================================
# Connection routing is handled by ~/.ssh/config (generated by setup-ssh.sh).
# Run ./scripts/setup-ssh.sh before using Ansible.
# =============================================================================

[control_nodes]
EOF

# Master control node — uses SSH Host alias for correct tunnel/proxy routing
printf "control-01 ansible_host=%s\n" "$MASTER_SSH_HOST" >> "$ANSIBLE_DIR/inventory.ini"

# Replica control nodes (control-02, control-03, ...) — SSH config routes via ProxyJump
for ((i=2; i<=CONTROL_COUNT; i++)); do
    printf "control-%02d ansible_host=control-%02d\n" $i $i >> "$ANSIBLE_DIR/inventory.ini"
done

cat >> "$ANSIBLE_DIR/inventory.ini" << 'EOF'

[worker_nodes]
EOF

# Worker nodes — SSH config routes via ProxyJump through control node or tunnel
for ((i=1; i<=WORKER_COUNT; i++)); do
    printf "worker-%02d ansible_host=worker-%02d\n" $i $i >> "$ANSIBLE_DIR/inventory.ini"
done

cat >> "$ANSIBLE_DIR/inventory.ini" << EOF

[k8s_cluster:children]
control_nodes
worker_nodes

[all:vars]
ansible_user=${ADMIN_USER}
EOF

echo ""
echo "Inventory generated: $ANSIBLE_DIR/inventory.ini"
echo ""
if [[ "$ADMIN_NODE_ENABLED" == "true" ]]; then
    echo "Routing: via admin node (ProxyJump)"
elif [[ -n "$TUNNEL_DOMAIN" ]]; then
    echo "Routing: via Cloudflare Tunnel ($TUNNEL_DOMAIN)"
else
    echo "Routing: direct connection"
fi
echo ""
echo "Prerequisites:"
echo "  1. Run ./scripts/setup-ssh.sh (generates ~/.ssh/config with proxy routing)"
echo "  2. Run source ./scripts/ssh-agent-setup.sh (loads SSH keys into agent)"
echo ""
echo "Test with:"
echo "  cd $ANSIBLE_DIR"
echo "  ansible all -m ping"
