#!/bin/bash

# =============================================================================
# Setup SSH Keys and Config after OpenTofu Apply
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SSH_DIR="$HOME/.ssh"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║          SSH Setup for Hetzner Kubernetes Cluster            ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check if we're in the right directory
if [[ ! -f "$SCRIPT_DIR/main.tf" ]]; then
    echo -e "${RED}Error: main.tf not found. Run this script from the OpenTofu project directory.${NC}"
    exit 1
fi

# Check if tofu/terraform is available
if command -v tofu &> /dev/null; then
    TF_CMD="tofu"
elif command -v terraform &> /dev/null; then
    TF_CMD="terraform"
else
    echo -e "${RED}Error: Neither 'tofu' nor 'terraform' found in PATH.${NC}"
    exit 1
fi

# Check if state exists
if [[ ! -f "$SCRIPT_DIR/terraform.tfstate" ]]; then
    echo -e "${RED}Error: terraform.tfstate not found. Run '$TF_CMD apply' first.${NC}"
    exit 1
fi

# Get cluster name from tfvars or use default
CLUSTER_NAME=$($TF_CMD output -raw cluster_name 2>/dev/null || echo "k8s-cluster")

echo -e "${YELLOW}Cluster Name: $CLUSTER_NAME${NC}"
echo ""

# Create SSH directory if needed
mkdir -p "$SSH_DIR"
chmod 700 "$SSH_DIR"

# Export Control Node SSH Key
echo -e "${GREEN}[1/4] Exporting Control Node SSH Key...${NC}"
CONTROL_KEY_FILE="$SSH_DIR/${CLUSTER_NAME}_control-node_key"
$TF_CMD output -raw control_node_ssh_private_key > "$CONTROL_KEY_FILE"
chmod 600 "$CONTROL_KEY_FILE"
echo -e "      Saved to: $CONTROL_KEY_FILE"

# Export Worker Node SSH Key
echo -e "${GREEN}[2/4] Exporting Worker Node SSH Key...${NC}"
WORKER_KEY_FILE="$SSH_DIR/${CLUSTER_NAME}_worker-node_key"
$TF_CMD output -raw worker_node_ssh_private_key > "$WORKER_KEY_FILE"
chmod 600 "$WORKER_KEY_FILE"
echo -e "      Saved to: $WORKER_KEY_FILE"

# Backup existing SSH config
echo -e "${GREEN}[3/4] Updating SSH Config...${NC}"
if [[ -f "$SSH_DIR/config" ]]; then
    # Check if cluster config already exists
    if grep -q "# ${CLUSTER_NAME} - Generated by OpenTofu" "$SSH_DIR/config" 2>/dev/null; then
        echo -e "${YELLOW}      Warning: SSH config for '$CLUSTER_NAME' already exists.${NC}"
        echo -e "${YELLOW}      Remove old entries manually or use a different cluster name.${NC}"
    else
        cp "$SSH_DIR/config" "$SSH_DIR/config.backup.$(date +%Y%m%d_%H%M%S)"
        echo "" >> "$SSH_DIR/config"
        $TF_CMD output -raw ssh_config_snippet >> "$SSH_DIR/config"
        echo -e "      SSH config updated (backup created)"
    fi
else
    $TF_CMD output -raw ssh_config_snippet > "$SSH_DIR/config"
    chmod 600 "$SSH_DIR/config"
    echo -e "      SSH config created"
fi

# Show connection info
echo -e "${GREEN}[4/4] Connection Information${NC}"
echo ""
CONTROL_IPV6=$($TF_CMD output -raw control_node_ipv6 2>/dev/null || echo "N/A")
CONTROL_PRIVATE=$($TF_CMD output -raw control_node_private_ip 2>/dev/null || echo "N/A")
ADMIN_USER=$($TF_CMD output -raw admin_user 2>/dev/null || echo "kubernetes-admin")

echo -e "╔══════════════════════════════════════════════════════════════╗"
echo -e "║ Control Node                                                  ║"
echo -e "╠══════════════════════════════════════════════════════════════╣"
echo -e "║ IPv6 (temporary): $CONTROL_IPV6"
echo -e "║ Private IP:       $CONTROL_PRIVATE"
echo -e "╠══════════════════════════════════════════════════════════════╣"
echo -e "║ Connect via IPv6 (temporary):                                ║"
echo -e "║   ssh -i $CONTROL_KEY_FILE $ADMIN_USER@$CONTROL_IPV6"
echo -e "╠══════════════════════════════════════════════════════════════╣"
echo -e "║ NEXT STEPS:                                                   ║"
echo -e "║ 1. SSH to control node using IPv6 command above              ║"
echo -e "║ 2. Install Cloudflare Tunnel:                                ║"
echo -e "║    sudo cloudflared service install <YOUR_TOKEN>             ║"
echo -e "║ 3. Set enable_public_ipv6 = false in terraform.tfvars       ║"
echo -e "║ 4. Run: $TF_CMD apply                                        ║"
echo -e "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo -e "${GREEN}Setup complete!${NC}"
