#!/bin/bash

# =============================================================================
# Setup SSH Keys and Config after OpenTofu Apply
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SSH_DIR="$HOME/.ssh"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║          SSH Setup for Hetzner Kubernetes Cluster            ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check if we're in the right directory
if [[ ! -f "$PROJECT_DIR/main.tf" ]]; then
    echo -e "${RED}Error: main.tf not found. Run this script from the OpenTofu project directory.${NC}"
    exit 1
fi

# Check if tofu/terraform is available
if command -v tofu &> /dev/null; then
    TF_CMD="tofu"
elif command -v terraform &> /dev/null; then
    TF_CMD="terraform"
else
    echo -e "${RED}Error: Neither 'tofu' nor 'terraform' found in PATH.${NC}"
    exit 1
fi

cd "$PROJECT_DIR"

# Check if state exists
if [[ ! -f "$PROJECT_DIR/terraform.tfstate" ]]; then
    echo -e "${RED}Error: terraform.tfstate not found. Run '$TF_CMD apply' first.${NC}"
    exit 1
fi

# Get cluster name and SSH key prefix from outputs
CLUSTER_NAME=$($TF_CMD output -raw cluster_name 2>/dev/null || echo "k8s-cluster")
SSH_KEY_PREFIX=$($TF_CMD output -raw ssh_key_prefix 2>/dev/null || echo "$CLUSTER_NAME")
ADMIN_NODE_ENABLED=$($TF_CMD output -raw enable_admin_node 2>/dev/null || echo "false")
TUNNEL_CONFIGURED=$($TF_CMD output -raw cloudflare_tunnel_configured 2>/dev/null || echo "false")

echo -e "${YELLOW}Cluster Name:   $CLUSTER_NAME${NC}"
echo -e "${YELLOW}SSH Key Prefix: $SSH_KEY_PREFIX${NC}"
echo ""

# Create SSH directory if needed
mkdir -p "$SSH_DIR"
chmod 700 "$SSH_DIR"

STEP=1
TOTAL=4
if [[ "$ADMIN_NODE_ENABLED" == "true" ]]; then
    TOTAL=5
fi

# Export Admin Node SSH Key (if enabled)
if [[ "$ADMIN_NODE_ENABLED" == "true" ]]; then
    echo -e "${GREEN}[$STEP/$TOTAL] Exporting Admin Node SSH Key...${NC}"
    ADMIN_KEY_FILE="$SSH_DIR/${SSH_KEY_PREFIX}_admin-node_key"
    ADMIN_KEY_CONTENT=$($TF_CMD output -raw admin_node_ssh_private_key 2>/dev/null || echo "")
    if [[ -n "$ADMIN_KEY_CONTENT" && "$ADMIN_KEY_CONTENT" != "Using custom key - manage privately" && "$ADMIN_KEY_CONTENT" != "Admin node disabled" ]]; then
        echo "$ADMIN_KEY_CONTENT" > "$ADMIN_KEY_FILE"
        chmod 600 "$ADMIN_KEY_FILE"
        echo -e "      Saved to: $ADMIN_KEY_FILE"
    else
        echo -e "${YELLOW}      Using custom key - skipping export${NC}"
    fi
    ((STEP++))
fi

# Export Control Node SSH Key
echo -e "${GREEN}[$STEP/$TOTAL] Exporting Control Node SSH Key...${NC}"
CONTROL_KEY_FILE="$SSH_DIR/${SSH_KEY_PREFIX}_control-node_key"
$TF_CMD output -raw control_node_ssh_private_key > "$CONTROL_KEY_FILE"
chmod 600 "$CONTROL_KEY_FILE"
echo -e "      Saved to: $CONTROL_KEY_FILE"
((STEP++))

# Export Worker Node SSH Key
echo -e "${GREEN}[$STEP/$TOTAL] Exporting Worker Node SSH Key...${NC}"
WORKER_KEY_FILE="$SSH_DIR/${SSH_KEY_PREFIX}_worker-node_key"
$TF_CMD output -raw worker_node_ssh_private_key > "$WORKER_KEY_FILE"
chmod 600 "$WORKER_KEY_FILE"
echo -e "      Saved to: $WORKER_KEY_FILE"
((STEP++))

# Backup existing SSH config
echo -e "${GREEN}[$STEP/$TOTAL] Updating SSH Config...${NC}"
if [[ -f "$SSH_DIR/config" ]]; then
    # Check if cluster config already exists
    if grep -q "# ${CLUSTER_NAME} - Generated by OpenTofu" "$SSH_DIR/config" 2>/dev/null; then
        echo -e "${YELLOW}      Warning: SSH config for '$CLUSTER_NAME' already exists.${NC}"
        echo -e "${YELLOW}      Remove old entries manually or use a different cluster name.${NC}"
    else
        cp "$SSH_DIR/config" "$SSH_DIR/config.backup.$(date +%Y%m%d_%H%M%S)"
        echo "" >> "$SSH_DIR/config"
        $TF_CMD output -raw ssh_config_snippet >> "$SSH_DIR/config"
        echo -e "      SSH config updated (backup created)"
    fi
else
    $TF_CMD output -raw ssh_config_snippet > "$SSH_DIR/config"
    chmod 600 "$SSH_DIR/config"
    echo -e "      SSH config created"
fi
((STEP++))

# Show connection info
echo -e "${GREEN}[$STEP/$TOTAL] Connection Information${NC}"
echo ""
CONTROL_PRIVATE=$($TF_CMD output -raw master_control_node_private_ip 2>/dev/null || echo "N/A")
ADMIN_USER=$($TF_CMD output -raw admin_user 2>/dev/null || echo "kubernetes-admin")

echo -e "╔══════════════════════════════════════════════════════════════╗"
if [[ "$ADMIN_NODE_ENABLED" == "true" ]]; then
    ADMIN_IPV6=$($TF_CMD output -raw admin_node_ipv6 2>/dev/null || echo "N/A")
    echo -e "║ Admin Node (temporary jump host)                            ║"
    echo -e "╠══════════════════════════════════════════════════════════════╣"
    echo -e "║ IPv6 (public):    $ADMIN_IPV6"
    echo -e "╠══════════════════════════════════════════════════════════════╣"
fi
echo -e "║ Control Node                                                  ║"
echo -e "╠══════════════════════════════════════════════════════════════╣"
echo -e "║ Private IP:       $CONTROL_PRIVATE"
echo -e "╠══════════════════════════════════════════════════════════════╣"
if [[ "$ADMIN_NODE_ENABLED" == "true" ]]; then
    echo -e "║ Connect via Admin Node:                                      ║"
    echo -e "║   ssh control-node"
else
    echo -e "║ Connect via Cloudflare Tunnel:                                ║"
    echo -e "║   ssh control-node"
fi
echo -e "╠══════════════════════════════════════════════════════════════╣"
echo -e "║ NEXT STEPS:                                                   ║"
echo -e "║ 1. SSH to control node using the command above              ║"
if [[ "$TUNNEL_CONFIGURED" == "true" ]]; then
echo -e "║ 2. Cloudflare Tunnel: auto-configured via tunnel token      ║"
else
echo -e "║ 2. Install Cloudflare Tunnel:                                ║"
echo -e "║    sudo cloudflared service install <YOUR_TOKEN>             ║"
echo -e "║    Hint: set cloudflare_tunnel_token in terraform.tfvars    ║"
fi
echo -e "║ 3. Set enable_admin_node = false in terraform.tfvars        ║"
echo -e "║ 4. Run: $TF_CMD apply                                        ║"
echo -e "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo -e "${GREEN}Setup complete!${NC}"
